# Generated by Django 6.0.4 on 2026-04-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='emoji',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
