# Generated by Django 6.0.4 on 2026-04-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_layanan_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tanggal_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
