# Generated by Django 6.0.4 on 2026-04-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_shipment_tanggal_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_shipment', to='backend.shipment'),
        ),
    ]
