# Generated by Django 6.0.4 on 2026-06-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_kategori_remove_shipment_dokumen_dokumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/'),
        ),
    ]
