# Generated by Django 6.0.4 on 2026-06-21 15:23

import backend.models
import backend.storage_backends
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_dokumen_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('task_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dokumen',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ['judul'], 'verbose_name_plural': 'Kategori'},
        ),
        migrations.AddField(
            model_name='dokumen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dokumen',
            name='judul',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='keterangan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='nama_file',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='ocr_engine',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='ocr_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='ocr_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='ocr_status',
            field=models.CharField(choices=[('pending', 'Menunggu OCR'), ('processing', 'Sedang Diproses'), ('done', 'Selesai'), ('failed', 'Gagal')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='ocr_teks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='tfidf_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='ukuran',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='upload_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='upload_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Menunggu Upload'), ('uploading', 'Sedang Upload'), ('uploaded', 'Terupload'), ('failed', 'Gagal')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_diupload', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kategori',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kategori',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='file',
            field=models.FileField(blank=True, null=True, storage=backend.storage_backends.DokumenS3Storage(), upload_to=backend.models.dokumen_upload_path),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='judul',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='dokumen',
            index=models.Index(fields=['upload_status'], name='backend_dok_upload__65ef96_idx'),
        ),
        migrations.AddIndex(
            model_name='dokumen',
            index=models.Index(fields=['ocr_status'], name='backend_dok_ocr_sta_4bbbcf_idx'),
        ),
        migrations.AddIndex(
            model_name='dokumen',
            index=models.Index(fields=['kategori'], name='backend_dok_kategor_62696f_idx'),
        ),
        migrations.AddIndex(
            model_name='dokumen',
            index=models.Index(fields=['client'], name='backend_dok_client__7e1031_idx'),
        ),
        migrations.AddIndex(
            model_name='dokumen',
            index=models.Index(fields=['shipment'], name='backend_dok_shipmen_ca4847_idx'),
        ),
        migrations.AddIndex(
            model_name='dokumen',
            index=models.Index(fields=['created_at'], name='backend_dok_created_1d1066_idx'),
        ),
        migrations.AddField(
            model_name='dokumentasklog',
            name='dokumen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='backend.dokumen'),
        ),
    ]
