# Generated by Django 6.0.4 on 2026-07-07 10:28

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_dokumentasklog_alter_dokumen_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=backend.storage_backends.DokumenS3Storage(), upload_to='foto_profil/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=backend.storage_backends.DokumenS3Storage(), upload_to='foto_team/'),
        ),
    ]
